name: Deploy Flutter Web to Cloudflare Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Flutter Web (with env)
        run: flutter build web --release --dart-define-from-file=env.json

      - name: Compute Cloudflare project name
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          if [ -z "${{ vars.CF_PAGES_PROJECT_NAME }}" ]; then
            # Default to repo name; must be lowercase and alphanumeric + hyphens
            echo "PROJECT_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]//g')" >> $GITHUB_ENV
          else
            echo "PROJECT_NAME=${{ vars.CF_PAGES_PROJECT_NAME }}" >> $GITHUB_ENV
          fi

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.PROJECT_NAME }}
          directory: build/web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
